1. Abordagens radicionais (Random Forest, Support Vector Machine e XGBoost)

### Bibliotecas e Dependências

In [21]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.3 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 28.1 MB/s  0:00:00

   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   --------------------------


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [39]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
df = pd.read_csv("C:/Users/05646078199/Projetos/Projeto-Mestrado/Analise-Linguistica/df_main.csv")

In [32]:
df.head()

,Index,Class,Abstract,id_texto,adjective_ratio,adverbs,content_words,flesch,function_words,sentences_per_paragraph,...,relative_pronouns_ratio,relative_pronouns_diversity_ratio,subjunctive_future_ratio,subjunctive_imperfect_ratio,subjunctive_present_ratio,subordinate_clauses,temporal_adjunct_ratio,adverbs_before_main_verb_ratio,verbal_time_moods_diversity,ratio_function_to_content_words
0,9524,Humana,Este artigo apresenta a ferramenta de autoria ...,9524,0.05882,0.01471,0.60294,17.59176,0.39706,4.0,...,0.00000,0.0,0.0,0.0,0.0,0.37500,0.00000,0.12500,1.0,0.65854
1,23303,Humana,"Recentemente, nota-se um grande crescimento da...",23303,0.07471,0.02299,0.54598,7.84748,0.45402,5.0,...,0.50000,0.5,0.0,0.0,0.0,0.81818,0.13333,0.18182,1.0,0.83158
2,24458,Humana,O advento da TV Digital tem contribuído para o...,24458,0.06122,0.02041,0.56122,11.39814,0.43878,5.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.40000,2.0,0.78182
3,23313,Humana,Este artigo descreve o uso de personas em inte...,23313,0.10204,0.04082,0.57143,20.23689,0.42857,4.0,...,0.33333,1.0,0.0,0.0,0.0,0.40000,0.00000,0.20000,1.0,0.75000
4,23320,Humana,Em diversas operações relacionadas ao gerencia...,23320,0.03650,0.00730,0.60584,28.67085,0.39416,6.0,...,0.40000,1.0,0.0,0.0,0.0,0.58824,0.06667,0.17647,1.0,0.65060


In [34]:
map_classes = {
    "Humana" : 1,
    "Gerada" : 2,
    "Polida_IA" : 3
}

In [35]:
df["label"] = df["Class"].map(map_classes)

In [29]:
df.dropna(inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4387 entries, 0 to 6377
Columns: 205 entries, Index to label
dtypes: float64(201), int64(2), object(2)
memory usage: 6.9+ MB


### Divisão em Treino e Teste

In [36]:
x = df.drop(columns=["Index", "Class", "Abstract", "id_texto", "label"])
y = df["label"]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42, stratify=y)

model = RandomForestClassifier(n_estimators=200, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [45]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.80      0.84      0.82       220
           2       0.85      0.86      0.85       219
           3       0.74      0.70      0.71       220

    accuracy                           0.80       659
   macro avg       0.80      0.80      0.80       659
weighted avg       0.80      0.80      0.80       659



In [46]:
print(confusion_matrix(y_test, y_pred))

[[184   6  30]
 [  6 188  25]
 [ 39  28 153]]
